export const tableHeadAppoint = [
  { key: "number", value: "Номер" },
  { key: "status", value: "Статус" },
  { key: "contractor", value: "Подрядчик" },
  { key: "object", value: "Объект" },
  { key: "problemDescription", value: "Описание проблемы" },
  { key: "photo", value: "Фото проблемы" },
  { key: "urgency", value: "Срочность" },
  { key: "itineraryOrder", value: "Маршрут" },
  { key: "completeDate", value: "Дата выполнения" },
  { key: "repairPrice", value: "Груз" },
  { key: "comment", value: "Комментарий" },
  { key: "legalEntity", value: "Юр. Лицо" },
  { key: "daysAtWork", value: "Сумма" },
]; 