import { TContractor, TExtContractor } from './contractors.types';
import { TDirectoryCategory } from './directoryCategory.types';

export type TRequest = {
  id: string;
  builder: string;
  checkPhoto: string | null;
  comment: string | null;
  commentAttachment: string | null;
  completeDate: string | null;
  completeDateRaw: string | null;
  contractor: TContractor | null;
  contractorManager: string | null;
  copiedRequestId: string | null;
  createdAt: string;
  createdAtRaw: string;
  daysAtWork: number;
  directoryCategory: TDirectoryCategory;
  exitDate: string;
  extContractor: TExtContractor | null;
  fileName: string | null;
  isExternal: boolean;
  itineraryOrder: number | null;
  legalEntity: string;
  managerId: string | null;
  managerTgId: string | null;
  number: number;
  object: string;
  objectId: string;
  planCompleteDate: string;
  planCompleteDateRaw: string | null;
  problemDescription: string | null;
  repairPrice: number | null;
  status: number;
  statusId: string | null;
  unit: string;
  urgency: string;
  urgencyId: string;
};
