const events = {
    STATUS_UPDATE: 'STATUS_UPDATE',
    USER_REGISTRATION_REQUEST: 'USER_REGISTRATION_REQUEST',
    USER_CONFIRM: 'USER_CONFIRM',
    REQUEST_ASSIGNED: 'REQUEST_ASSIGNED',
    COMMENT_CREATE: 'COMMENT_CREATE',
    USER_TG_BIND_OK: 'USER_TG_BIND_OK',
} as const;

export default events;
