export const testData = [
  {
    id: 1,
    status: "Активный",
    client: "Клиент А",
    loading: "Да",
    unloading: "Нет",
    typeCargo: "Тип X",
    executor: "Джон Доу",
    numberCar: "ABC123",
    driver: "Джейн Смит",
    cost: "12750 руб.",
  },
  {
    id: 2,
    status: "Неактивный",
    client: "Клиент Б",
    loading: "Нет",
    unloading: "Да",
    typeCargo: "Тип Y",
    executor: "Боб Джонсон",
    numberCar: "DEF456",
    driver: "Майк Дэвис",
    cost: "17850 руб.",
  },
  {
    id: 3,
    status: "Активный",
    client: "Клиент В",
    loading: "Да",
    unloading: "Да",
    typeCargo: "Тип Z",
    executor: "Алиса Иванова",
    numberCar: "GHI789",
    driver: "Петр Сидоров",
    cost: "25500 руб.",
  },
  {
    id: 4,
    status: "Неактивный",
    client: "Клиент Г",
    loading: "Нет",
    unloading: "Нет",
    typeCargo: "Тип A",
    executor: "Ольга Петрова",
    numberCar: "JKL012",
    driver: "Андрей Кузнецов",
    cost: "10200 руб.",
  },
  {
    id: 5,
    status: "Активный",
    client: "Клиент Д",
    loading: "Да",
    unloading: "Нет",
    typeCargo: "Тип Б",
    executor: "Иван Смирнов",
    numberCar: "MNO345",
    driver: "Екатерина Соколова",
    cost: "18000 руб.",
  },
];
