version: '3'
services:
  db:
    container_name:
      sova-fix-db
    image: postgres:15
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PWD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5433:5432"
    command: -p 5433
    networks:
      - sova-fix-network
    volumes:
      - pgdata:/var/lib/postgresql/data

  server:
    container_name: sova-fix-server
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV}
    networks:
      - sova-fix-network

  bot:
    depends_on:
      - server
    env_file:
      - .env
    container_name: sova-fix-bot
    build:
      context: ../bot
      dockerfile: Dockerfile
    restart: always
    networks:
      - sova-fix-network

networks:
  sova-fix-network:

volumes:
  pgdata:
