name: Docker Image CI for GHCR

on:
  push:
    branches:
      - main

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log into registry ghcr.io
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}

      - name: Build and push the api container
        run: |
          docker build -t ghcr.io/simai1/sova-fix/sova-api:latest ./api
          docker push ghcr.io/simai1/sova-fix/sova-api:latest

      - name: Build and push the bot container
        run: |
          docker build -t ghcr.io/simai1/sova-fix/sova-bot:latest ./bot
          docker push ghcr.io/simai1/sova-fix/sova-bot:latest

      - name: Notify Jenkins Pipeline
        run: |
          curl -X POST ${{ secrets.JENKINS_URL }} \
          -d '{"ref": "refs/heads/main"}'
