name: Docker Image CI for GHCR

on:
  push

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GHCR
        run: |
          echo ${{ GH_PAT }} | sudo docker login ghcr.io -u simai1 --password-stdin

      - name: Build and push the api container
        run: |
          docker build -t ghcr.io/simai1/sova-fix/sova-api:latest ./api
          docker push ghcr.io/simai1/sova-fix/sova-api:latest

      - name: Build and push the bot container
        run: |
          docket build -t ghcr.io/simai1/sova-fix/sova-bot:latest ./bot
          docker push ghcr.io/simai1/sova-fix/sova-bot:latest
